---
- name: install pip and virtualenv (Ubuntu)
  apt: name={{ item }} state=present
  with_items:
    - build-essential
    - python-pip
    - python-dev
  when: ansible_distribution == 'Ubuntu'
  become: yes
  become_method: sudo

- name: install virtualenv
  pip:
    name: ['virtualenv', 'jedi']
  when: ansible_os_family == 'Darwin'
