---
- name: install oh-my-zsh
  git:
    repo: https://github.com/robbyrussell/oh-my-zsh.git
    dest: ~/.oh-my-zsh

- name: setup zshrc file
  copy: >
    dest=~/.zshrc
    src=zshrc

- name: add prose theme
  copy: >
    dest=~/.oh-my-zsh/custom/themes/prose.zsh-theme
    src=prose.zsh-theme

- name: add zsh to list of shells
  lineinfile: >
    backup=yes
    dest=/etc/shells
    regexp=^/usr/local/bin/zsh
    line=/usr/local/bin/zsh
  sudo: yes
  when: ansible_os_family == 'Darwin'

- name: change to zsh (Mac)
  shell: chsh -s /usr/local/bin/zsh {{ ansible_env.USER }}
  when: ansible_os_family == 'Darwin'

- name: change to zsh (Ubuntu)
  shell: chsh -s /usr/bin/zsh {{ ansible_env.USER }}
  become: yes
  become_method: sudo
  when: ansible_distribution == 'Ubuntu'
