---
- name: Add Dropbox KeyServer
  sudo: True
  command: apt-key adv --keyserver pgp.mit.edu --recv-keys 1C61A2656FB57B7E4DE0F4C1FC918B335044912E
  when: ansible_distribution == 'Ubuntu'

- name: Add Dropbox PPA Repo
  sudo: True
  command: add-apt-repository "deb http://linux.dropbox.com/ubuntu {{ ansible_lsb.codename }} main"
  when: ansible_distribution == 'Ubuntu'

- name: update apt
  apt: update_cache=yes
  when: ansible_distribution == 'Ubuntu'
  become: yes
  become_method: sudo

- name: Install Dropbox
  sudo: True
  apt: pkg=dropbox state=installed
  when: ansible_distribution == 'Ubuntu'
