- name: create folder for terminal theme
  file:
    path: ~/.terminal
    state: directory

- name: download ocean theme
  get_url:
    url: https://raw.githubusercontent.com/mdo/ocean-terminal/master/terminal-ocean-dark.terminal
    dest: ~/.terminal/terminal-ocean-dark.terminal
  when: ansible_os_family == 'Darwin'

- name: open themes in Terminal
  shell: open -g ~/.terminal/terminal-ocean-dark.terminal
  ignore_errors: yes
  when: ansible_os_family == 'Darwin'

- name: 'Terminal: Set startup window'
  shell: 'defaults write com.apple.Terminal "Startup Window Settings" -string terminal-ocean-dark'
  when: ansible_os_family == 'Darwin'

- name: 'Terminal: Set default window'
  shell: 'defaults write com.apple.Terminal "Default Window Settings" -string terminal-ocean-dark'
  when: ansible_os_family == 'Darwin'
